name: Deploy Laravel to AWS Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          docker build -t 043309367638.dkr.ecr.us-east-1.amazonaws.com/astudio-laravel-api:${{ github.sha }} .
          docker push 043309367638.dkr.ecr.us-east-1.amazonaws.com/astudio-laravel-api:${{ github.sha }}

      - name: Deploy Laravel on Swarm (Only If Service Doesn't Exist)
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} ec2-user@your-ec2-ip "
          if ! docker service ls | grep -q 'laravel-stack_laravel-api'; then
            docker service create \
              --name laravel-stack_laravel-api \
              --network laravel-network \
              --publish 8000:8000 \
              --env APP_ENV=local \
              --env DB_HOST=db \
              --env DB_DATABASE=laravel \
              --env DB_USERNAME=root \
              --env DB_PASSWORD=root \
              043309367638.dkr.ecr.us-east-1.amazonaws.com/astudio-laravel-api:${{ github.sha }}
          else
            docker service update --image 043309367638.dkr.ecr.us-east-1.amazonaws.com/astudio-laravel-api:${{ github.sha }} laravel-stack_laravel-api
          fi"
